function Profile = readDFM17(filename, dataLines)
%IMPORTFILE Import data from a text file
%  PROFILE = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  PROFILE = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Profile = importfile("C:\Users\Level1Zach\Desktop\W8_L1_1100UTC_072220_ZASUS_Profile.txt", [21, 4780]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jul-2020 12:05:19

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [21, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 19);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Time", "P", "T", "Hu", "Ws", "Wd", "Long", "Lat", "Alt", "Geopot", "MRI", "RI", "Dewp", "VirtTemp", "Rs", "Elevation", "Azimuth", "Range", "D"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
Profile = readtable(filename, opts);

end