function RS92import = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  DIGITALSONDE2020060918ZH2514403PTU = IMPORTFILE(FILENAME) reads data
%  from text file FILENAME for the default selection.  Returns the data
%  as a table.
%
%  DIGITALSONDE2020060918ZH2514403PTU = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  digitalsonde2020060918ZH2514403ptu = importfile("E:\MATLAB Drive\Eclipse\digitalsonde2020060918Z_H2514403_ptu.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Jun-2020 21:42:21

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Frame", "Pressure", "Temp", "Humidity", "GPSalt", "GPSwinddir", "GPSwindspeed"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
RS92import = readtable(filename, opts);

end