# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProjectGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1101, 893)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 871, 101))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_Open = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_Open.setGeometry(QtCore.QRect(10, 20, 211, 23))
        self.pushButton_Open.setObjectName("pushButton_Open")
        self.textEdit_filename = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_filename.setGeometry(QtCore.QRect(280, 20, 571, 71))
        self.textEdit_filename.setObjectName("textEdit_filename")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 120, 671, 691))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_flightpath = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_flightpath.setGeometry(QtCore.QRect(10, 10, 651, 391))
        self.graphicsView_flightpath.setObjectName("graphicsView_flightpath")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_balloonplots = QtWidgets.QGraphicsView(self.tab_2)
        self.graphicsView_balloonplots.setGeometry(QtCore.QRect(10, 10, 651, 641))
        self.graphicsView_balloonplots.setObjectName("graphicsView_balloonplots")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.plainTextEdit_FlightReport = QtWidgets.QPlainTextEdit(self.tab_3)
        self.plainTextEdit_FlightReport.setGeometry(QtCore.QRect(10, 10, 651, 421))
        self.plainTextEdit_FlightReport.setObjectName("plainTextEdit_FlightReport")
        self.tabWidget.addTab(self.tab_3, "")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(690, 130, 381, 481))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 61, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(30, 90, 81, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(50, 300, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(50, 240, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(50, 270, 47, 13))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 440, 101, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(30, 380, 121, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(20, 410, 71, 16))
        self.label_9.setObjectName("label_9")
        self.lineEdit_LaunchDia = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_LaunchDia.setGeometry(QtCore.QRect(110, 30, 113, 20))
        self.lineEdit_LaunchDia.setObjectName("lineEdit_LaunchDia")
        self.lineEdit_alt = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_alt.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.lineEdit_alt.setObjectName("lineEdit_alt")
        self.lineEdit_mass = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_mass.setGeometry(QtCore.QRect(110, 90, 113, 20))
        self.lineEdit_mass.setObjectName("lineEdit_mass")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(230, 90, 71, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(230, 30, 51, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(230, 60, 47, 13))
        self.label_12.setObjectName("label_12")
        self.lineEdit_Steps = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Steps.setGeometry(QtCore.QRect(130, 440, 113, 20))
        self.lineEdit_Steps.setObjectName("lineEdit_Steps")
        self.lineEdit_FlightTime = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_FlightTime.setGeometry(QtCore.QRect(130, 410, 113, 20))
        self.lineEdit_FlightTime.setObjectName("lineEdit_FlightTime")
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setGeometry(QtCore.QRect(260, 410, 71, 16))
        self.label_13.setObjectName("label_13")
        self.comboBox_balloon = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_balloon.setGeometry(QtCore.QRect(130, 240, 101, 22))
        self.comboBox_balloon.setObjectName("comboBox_balloon")
        self.comboBox_wind = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_wind.setGeometry(QtCore.QRect(130, 270, 101, 22))
        self.comboBox_wind.setObjectName("comboBox_wind")
        self.comboBox_glider = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_glider.setGeometry(QtCore.QRect(130, 300, 101, 22))
        self.comboBox_glider.setObjectName("comboBox_glider")
        self.pushButton_Launch = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_Launch.setGeometry(QtCore.QRect(110, 340, 75, 23))
        self.pushButton_Launch.setObjectName("pushButton_Launch")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(30, 120, 81, 20))
        self.label_33.setObjectName("label_33")
        self.lineEdit_TimeofDay = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_TimeofDay.setGeometry(QtCore.QRect(110, 120, 113, 20))
        self.lineEdit_TimeofDay.setObjectName("lineEdit_TimeofDay")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(30, 180, 81, 20))
        self.label_34.setObjectName("label_34")
        self.lineEdit_DayofYear = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_DayofYear.setGeometry(QtCore.QRect(110, 180, 113, 20))
        self.lineEdit_DayofYear.setObjectName("lineEdit_DayofYear")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(230, 120, 151, 20))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(230, 180, 81, 20))
        self.label_36.setObjectName("label_36")
        self.label_54 = QtWidgets.QLabel(self.groupBox_2)
        self.label_54.setGeometry(QtCore.QRect(230, 140, 151, 20))
        self.label_54.setObjectName("label_54")
        self.lineEdit_Latitude = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_Latitude.setGeometry(QtCore.QRect(110, 210, 113, 20))
        self.lineEdit_Latitude.setObjectName("lineEdit_Latitude")
        self.label_55 = QtWidgets.QLabel(self.groupBox_2)
        self.label_55.setGeometry(QtCore.QRect(230, 210, 81, 20))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.groupBox_2)
        self.label_56.setGeometry(QtCore.QRect(30, 210, 81, 20))
        self.label_56.setObjectName("label_56")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(800, 620, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(730, 650, 221, 201))
        self.frame.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(20, 10, 161, 21))
        self.label_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(30, 40, 111, 21))
        self.label_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame)
        self.label_16.setGeometry(QtCore.QRect(30, 70, 111, 21))
        self.label_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame)
        self.label_17.setGeometry(QtCore.QRect(30, 100, 111, 21))
        self.label_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.frame)
        self.label_18.setGeometry(QtCore.QRect(30, 130, 111, 21))
        self.label_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame)
        self.label_19.setGeometry(QtCore.QRect(30, 160, 111, 21))
        self.label_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_19.setObjectName("label_19")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Strato Glider and Balloon Analysis"))
        self.groupBox.setTitle(_translate("Dialog", "Balloon File"))
        self.pushButton_Open.setText(_translate("Dialog", "Open and Read a Balloon File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Flight Path"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Balloon Plots"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Flight Report"))
        self.groupBox_2.setTitle(_translate("Dialog", "Balloon Flight Simulation"))
        self.label.setText(_translate("Dialog", "Launch Dia."))
        self.label_2.setText(_translate("Dialog", "Altitude"))
        self.label_3.setText(_translate("Dialog", "Payload Mass"))
        self.label_4.setText(_translate("Dialog", "Glider"))
        self.label_5.setText(_translate("Dialog", "Balloon"))
        self.label_6.setText(_translate("Dialog", "Wind"))
        self.label_7.setText(_translate("Dialog", "Number of Steps"))
        self.label_8.setText(_translate("Dialog", "Simulation Control"))
        self.label_9.setText(_translate("Dialog", "Flight Time"))
        self.label_10.setText(_translate("Dialog", "kg"))
        self.label_11.setText(_translate("Dialog", "m"))
        self.label_12.setText(_translate("Dialog", "m"))
        self.label_13.setText(_translate("Dialog", "s"))
        self.pushButton_Launch.setText(_translate("Dialog", "Launch"))
        self.label_33.setText(_translate("Dialog", "Time of Day"))
        self.lineEdit_TimeofDay.setText(_translate("Dialog", "12"))
        self.label_34.setText(_translate("Dialog", "Day of Year"))
        self.lineEdit_DayofYear.setText(_translate("Dialog", "24"))
        self.label_35.setText(_translate("Dialog", "Military Time, no minutes"))
        self.label_36.setText(_translate("Dialog", "1-365"))
        self.label_54.setText(_translate("Dialog", "ex. 3:30=15.5"))
        self.lineEdit_Latitude.setText(_translate("Dialog", "36.11"))
        self.label_55.setText(_translate("Dialog", "degrees"))
        self.label_56.setText(_translate("Dialog", "Latitude"))
        self.pushButton.setText(_translate("Dialog", "Exit"))
        self.label_14.setText(_translate("Dialog", "Honors Team Members:"))
        self.label_15.setText(_translate("Dialog", "Dylan Luper"))
        self.label_16.setText(_translate("Dialog", "Kevin Bruggemeyer"))
        self.label_17.setText(_translate("Dialog", "Lindsay Cordier"))
        self.label_18.setText(_translate("Dialog", "Tyler Blackshare"))
        self.label_19.setText(_translate("Dialog", "Ethan Lane"))

